version: '3'

networks:
  default:
    driver: bridge
  sascha_frontend:
    external: false

services:
  sascha_frontend:
    build:
      context: .
      dockerfile: container/Containerfile
    image: registry.zehringer.me/sascha_frontend:latest
    container_name: sascha-frontend
    restart: always
    # env_file:
    #   - .env
    networks:
      - default
      - sascha_frontend
    ports:
      - "8000:80"

